# render.yaml
# This file tells Render how to build and deploy your services.

services:
  # 1. A Go Web Service for your backend API
  - type: web
    name: go-backend
    runtime: go
    # Explicitly define the build and start commands to handle the monorepo structure
    buildCommand: "cd backend && go build -o ../app ."
    startCommand: "./app"
    plan: free
    healthCheckPath: /api/sonnet

  # 2. A Static Site for your Svelte frontend
  - type: static
    name: svelte-frontend
    # Look for the Svelte code in the 'frontend' directory
    rootDir: frontend
    # The command to build your Svelte app
    buildCommand: npm install && npm run build
    # The directory containing the built static files
    publishDir: dist
    plan: free
    # Routing rules to handle a Single Page Application (SPA) and the API
    routes:
      # Proxy all requests starting with /api to the backend service
      - type: rewrite
        source: /api/*
        destination: http://go-backend/api/*
      # Rewrite all other paths to index.html for SPA routing
      - type: rewrite
        source: /*
        destination: /index.html
