# render.yaml
# This file tells Render how to build and deploy your services.

services:
  # 1. A Go Web Service for your backend API
  - type: web
    name: go-backend
    runtime: go
    # The build command is now simpler since go.mod is in the root
    buildCommand: "go build -o app ."
    startCommand: "./app"
    plan: free
    healthCheckPath: /api/sonnet

  # 2. A Static Site for your Svelte frontend
  - type: static
    name: svelte-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    plan: free
    routes:
      # Proxy API requests to the backend service
      - type: rewrite
        source: /api/*
        destination: http://go-backend
      # Rewrite all other paths to index.html for SPA routing
      - type: rewrite
        source: /*
        destination: /index.html
