# render.yaml
# This file tells Render how to build and deploy your services.

services:
  # 1. A Go Web Service for your backend API
  - type: web
    name: go-backend
    runtime: go
    # Look for the Go code in the 'backend' directory
    rootDir: backend
    # The command to build your Go application
    buildGo: .
    # Render provides a free plan for web services
    plan: free
    # Health check to ensure the service is running
    healthCheckPath: /api/sonnet

  # 2. A Static Site for your Svelte frontend
  - type: static
    name: svelte-frontend
    # Look for the Svelte code in the 'frontend' directory
    rootDir: frontend
    # The command to build your Svelte app
    buildCommand: npm install && npm run build
    # The directory containing the built static files
    publishDir: dist
    # Render provides a free, fast CDN for static sites
    plan: free
    # Routing rules to handle a Single Page Application (SPA) and the API
    routes:
      # Proxy all requests starting with /api to the backend service
      - type: rewrite
        source: /api/*
        destination: https://go-backend.onrender.com/api/*
      # Rewrite all other paths to index.html for SPA routing
      - type: rewrite
        source: /*
        destination: /index.html
